# Data Wrangling
- Data wrangling (also known as data munging or data cleaning) is the process of transforming raw, messy, or unstructured data into a clean, structured, and usable format suitable for analysis, visualization, or modeling.
- Simple Definition
- Data wrangling = Getting data from its “real-world” messy state into a tidy, analysis-ready state.
# Why Data Wranling Matters??
- In real-world data science projects:
- 80% of the time is spent on data wrangling
- Only 20% on actual modeling/visualization
- Raw data is rarely perfect — it often has:
- Missing values
- Inconsistent formats (e.g., dates as strings)
- Duplicates
- Wrong data types
- Outliers
- Mixed case text
- Unnecessary columns
# Key Steps in Data Wrangling
### Gathering/Ingestion
- Load data from files (CSV, Excel), databases, APIs, web pages
### Assessing
- Explore: df.head(), df.info(), df.describe(), check for missing/duplicates
### Cleaning
- Handle missing values (drop/fill/impute)
- Remove duplicates
- Fix incorrect values
### Transforming
- Rename columns
- Change data types (e.g., string → datetime)
 - Create new features (e.g., age from birth year)

## Hierarchical Indexing (MultiIndex) in Pandas

Hierarchical indexing, also known as **MultiIndex**, allows pandas objects (Series or DataFrame) to have **multiple levels of indexing on one axis**. It enables representation of higher-dimensional data in a lower-dimensional structure.

With hierarchical indexing, each data point is identified by **more than one index label**, creating a hierarchy of indexes.

### Key Features
- Allows **multiple index levels** for rows or columns.
- Helps organize **complex datasets with grouped labels**.
- Supports powerful **data reshaping operations** such as `stack()` and `unstack()`.

### Example

```python
import pandas as pd

data = pd.Series(
    [10, 20, 30, 40],
    index=[['A', 'A', 'B', 'B'], [1, 2, 1, 2]]
)

print(data)

Output

A  1    10
   2    20
B  1    30
   2    40
dtype: int64

In [1]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
pd.options.display.max_columns = 20

In [2]:
np.random.seed(12345)

In [3]:
import matplotlib.pyplot as plt
plt.rc('figure',figsize = (10,6))

In [4]:
data = pd.Series(np.random.uniform(size = 9),
                 index = [['a','a','a','b','b','c','c','d','d'],
                          [1,2,3,1,3,1,2,2,3]])
data

a  1    0.929616
   2    0.316376
   3    0.183919
b  1    0.204560
   3    0.567725
c  1    0.595545
   2    0.964515
d  2    0.653177
   3    0.748907
dtype: float64

In [5]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [6]:
data['b']

1    0.204560
3    0.567725
dtype: float64

In [7]:
data['b':'c']

b  1    0.204560
   3    0.567725
c  1    0.595545
   2    0.964515
dtype: float64

In [8]:
data.loc[['b','d']]

b  1    0.204560
   3    0.567725
d  2    0.653177
   3    0.748907
dtype: float64

In [9]:
data.loc[:,2]

a    0.316376
c    0.964515
d    0.653177
dtype: float64

In [10]:
udata = data.unstack()  
# unstack() ---> moves the index level to columns
# stack() ---> moves the columns back to the index
udata

          1         2         3
a  0.929616  0.316376  0.183919
b  0.204560       NaN  0.567725
c  0.595545  0.964515       NaN
d       NaN  0.653177  0.748907

In [11]:
udata.unstack()

1  a    0.929616
   b    0.204560
   c    0.595545
   d         NaN
2  a    0.316376
   b         NaN
   c    0.964515
   d    0.653177
3  a    0.183919
   b    0.567725
   c         NaN
   d    0.748907
dtype: float64

In [12]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
                     columns=[["Ohio", "Ohio", "Colorado"],
                              ["Green", "Red", "Green"]])
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [13]:
frame.index.names = ["key1", "key2"]
frame.columns.names = ["state", "color"]
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [14]:
# Reordering and Sorting Levels

In [15]:
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [16]:
frame.sort_index(level =1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [17]:
frame.swaplevel(0,1).sort_index(level = 0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [18]:
# Summary Statistics by Level

In [19]:
frame.groupby(level = 'key2').sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [20]:
frame.groupby(level="color", axis="columns").sum()

/var/folders/by/1y9dyrg52t3_69n_jld52myh0000gn/T/ipykernel_64611/1417732070.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level="color", axis="columns").sum()

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

# Indexing with a DataFrame's Column

In [22]:
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                      "c": ["one", "one", "one", "two", "two",
                            "two", "two"],
                      "d": [0, 1, 2, 0, 1, 2, 3]})
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [23]:
frame2 = frame.set_index(['c','d'])
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [24]:
frame.set_index(['c','d'],drop = False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [25]:
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

# Merging and Combining Datasets
#### Ways of combining pandas objects
### pandas.merge

- Connect rows in DataFrames based on one or more keys. This will be familiar to users of SQL or other relational databases, as it implements database join operations.

### pandas.concat

- Concatenate or “stack” objects together along an axis.

### combine_first

- Splice together overlapping data to fill in missing values in one object with values from another.

In [26]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [27]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [32]:
pd.merge(df1,df2) # performs the join through common key,only the common keys are left others are ignored

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [33]:
pd.merge(df1,df2,on = 'key')  # Inner join is performed defaultly when merge operation is performed

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [31]:
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})
pd.merge(df3, df4, left_on="lkey", right_on="rkey")

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [34]:
# Outer Merge---> it keeps all the keysb from both DF ,filling missing values with NaN
pd.merge(df1, df2, how="outer")
pd.merge(df3, df4, left_on="lkey", right_on="rkey", how="outer")

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

In [35]:
# how = 'inner'--> use only the key combo observed in both tables
# how  = 'left' ---> use all key combination found in the left tables
# how = 'right' --> use all key combination found in right table 
# how = 'outer'  --> use all key combination observed in both tables together

In [36]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": pd.Series(range(6), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "a", "b", "d"],
                    "data2": pd.Series(range(5), dtype="Int64")})
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [37]:
df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [39]:
pd.merge(df1,df2,on = 'key', how = 'left' )  # only keep keys from the left side and fill the value nan for the data in right side

   key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [40]:
pd.merge(df1,df2, on = 'key', how = 'right')

   key  data1  data2
0    a      2      0
1    a      4      0
2    b      0      1
3    b      1      1
4    b      5      1
5    a      2      2
6    a      4      2
7    b      0      3
8    b      1      3
9    b      5      3
10   d   <NA>      4

In [41]:
pd.merge(df1,df2, on = 'key', how = 'outer')

   key  data1  data2
0    a      2      0
1    a      2      2
2    a      4      0
3    a      4      2
4    b      0      1
5    b      0      3
6    b      1      1
7    b      1      3
8    b      5      1
9    b      5      3
10   c      3   <NA>
11   d   <NA>      4

# Merge with Multiple Keys

In [42]:
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                     "key2": ["one", "two", "one"],
                     "lval": pd.Series([1, 2, 3], dtype='Int64')})
right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                      "key2": ["one", "one", "one", "two"],
                      "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})

In [43]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [44]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [45]:
pd.merge(left, right, on=["key1", "key2"], how="outer")

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

In [47]:
pd.merge(left, right, on="key1")

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [48]:
left1 = pd.DataFrame({"key": ["a", "b", "a", "a", "b", "c"],
                      "value": pd.Series(range(6), dtype="Int64")})
right1 = pd.DataFrame({"group_val": [3.5, 7]}, index=["a", "b"])
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [49]:
right1

   group_val
a        3.5
b        7.0

In [50]:
pd.merge(left1, right1, left_on="key", right_index=True)

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

In [51]:
pd.merge(left1, right1, left_on="key", right_index=True, how="outer")

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

# Concatenating Along an Axis

In [52]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
np.concatenate([arr,arr],axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [55]:
s1 = pd.Series([0, 1], index=["a", "b"], dtype="Int64")
s2 = pd.Series([2, 3, 4], index=["c", "d", "e"], dtype="Int64")
s3 = pd.Series([5, 6], index=["f", "g"], dtype="Int64")

In [56]:
s1

a    0
b    1
dtype: Int64

In [57]:
s2

c    2
d    3
e    4
dtype: Int64

In [58]:
s3

f    5
g    6
dtype: Int64

In [59]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [60]:
pd.concat([s1, s2, s3], axis="columns")

      0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [61]:
s4 = pd.concat([s1, s3])
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [62]:
pd.concat([s1, s4], axis="columns")

      0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [64]:
pd.concat([s1, s4], axis="columns", join="inner")

   0  1
a  0  0
b  1  1

In [65]:
result = pd.concat([s1, s1, s3], keys=["one", "two", "three"])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: Int64

In [66]:
result.unstack()

          a     b     f     g
one       0     1  <NA>  <NA>
two       0     1  <NA>  <NA>
three  <NA>  <NA>     5     6

In [67]:
pd.concat([s1, s2, s3], axis="columns", keys=["one", "two", "three"])

    one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

# Combining Data With Overlap

In [68]:
a = pd.Series([np.nan, 2.5, 0.0, 3.5, 4.5, np.nan],
              index=["f", "e", "d", "c", "b", "a"])
b = pd.Series([0., np.nan, 2., np.nan, np.nan, 5.],
              index=["a", "b", "c", "d", "e", "f"])
a
b
np.where(pd.isna(a), b, a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [69]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [70]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [71]:
a.combine_first(b)

a    0.0
b    4.5
c    3.5
d    0.0
e    2.5
f    5.0
dtype: float64

In [73]:
df1 = pd.DataFrame({"a": [1., np.nan, 5., np.nan],
                    "b": [np.nan, 2., np.nan, 6.],
                    "c": range(2, 18, 4)})
df2 = pd.DataFrame({"a": [5., 4., np.nan, 3., 7.],
                    "b": [np.nan, 3., 4., 6., 8.]})
df1
df2
df1.combine_first(df2)

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

# Reshaping and Pivoting
#### stack
- This “rotates” or pivots from the columns in the data to the rows.
### unstack
- This pivots from the rows into the columns.

In [74]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(["Ohio", "Colorado"], name="state"),
                    columns=pd.Index(["one", "two", "three"],
                    name="number"))
data

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [75]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [76]:
result.unstack()

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [77]:
result.unstack(level=0)
result.unstack(level="state")

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [78]:
s1 = pd.Series([0, 1, 2, 3], index=["a", "b", "c", "d"], dtype="Int64")
s2 = pd.Series([4, 5, 6], index=["c", "d", "e"], dtype="Int64")
data2 = pd.concat([s1, s2], keys=["one", "two"])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [79]:
data2.unstack()

        a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [81]:
data2.unstack().stack()

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [82]:
data2.unstack().stack(dropna = False)

/var/folders/by/1y9dyrg52t3_69n_jld52myh0000gn/T/ipykernel_64611/3506830189.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  data2.unstack().stack(dropna = False)

one  a       0
     b       1
     c       2
     d       3
     e    <NA>
two  a    <NA>
     b    <NA>
     c       4
     d       5
     e       6
dtype: Int64

In [83]:
df = pd.DataFrame({"left": result, "right": result + 5},
                  columns=pd.Index(["left", "right"], name="side"))
df
df.unstack(level="state")

side   left          right
state  Ohio Colorado  Ohio Colorado
number
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [84]:
df.unstack(level="state").stack(level="side")

/var/folders/by/1y9dyrg52t3_69n_jld52myh0000gn/T/ipykernel_64611/1359610506.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.unstack(level="state").stack(level="side")

state         Ohio  Colorado
number side
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

# Pivoting Long to Wide Format

In [86]:
# data = pd.read_csv("data/macrodata.csv")
# data = data.loc[:, ["year", "quarter", "realgdp", "infl", "unemp"]]
# data.head()

In [87]:
df = pd.DataFrame({"key": ["foo", "bar", "baz"],
                   "A": [1, 2, 3],
                   "B": [4, 5, 6],
                   "C": [7, 8, 9]})
df

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [89]:
melted = pd.melt(df,id_vars = 'key')
melted

#pd.melt reshapes the data from wide to long format
# id_vars='key' → keep this column as it is (don’t melt it)

# All other columns (A, B, C) → melted into two columns:

# variable → the original column name (A/B/C)

# value → the value in that column

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [90]:
reshaped = melted.pivot(index="key", columns="variable",
                        values="value")
reshaped

variable  A  B  C
key
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [91]:
reshaped.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [93]:
pd.melt(df, id_vars="key", value_vars=["A", "B"])
# id_vars = 'key' --> keep this column as in
#

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [94]:
pd.melt(df, value_vars=["A", "B", "C"])
pd.melt(df, value_vars=["key", "A", "B"])

  variable value
0      key   foo
1      key   bar
2      key   baz
3        A     1
4        A     2
5        A     3
6        B     4
7        B     5
8        B     6