# Softmax Regression

Softmax Regression is an extension of Logistic Regression used for **multi-class classification** problems where the target variable has more than two classes.

### Key Points
- Predicts probabilities for multiple classes.
- Uses the **Softmax Function** to convert scores into probabilities.
- The sum of all class probabilities equals 1.

### Softmax Formula

$$
P(y=i|x)=\frac{e^{z_i}}{\sum_{j=1}^{K} e^{z_j}}
$$

Where:
- $z_i$ = score (logit) for class $i$
- $K$ = total number of classes

---

# Training Intuition

The goal of training is to find the best weights and biases that minimize prediction errors.

### Steps
1. Initialize weights randomly.
2. Calculate class scores.
3. Apply Softmax to obtain probabilities.
4. Compute loss using Cross-Entropy.
5. Update weights using Gradient Descent.
6. Repeat until convergence.

### Score Calculation

$$
z = Wx + b
$$

Where:
- $W$ = weight matrix
- $x$ = input features
- $b$ = bias vector

---

# Loss Function

Softmax Regression uses **Categorical Cross-Entropy Loss**.

### Formula

$$
L = -\sum_{i=1}^{K} y_i \log(\hat{y}_i)
$$

Where:
- $y_i$ = actual class label (one-hot encoded)
- $\hat{y}_i$ = predicted probability

### For N Samples

$$
J = -\frac{1}{N}\sum_{n=1}^{N}\sum_{i=1}^{K}
y_{ni}\log(\hat{y}_{ni})
$$

### Purpose
- Penalizes incorrect predictions.
- Lower loss indicates better model performance.

---

# Prediction

After training, the model predicts the class with the highest probability.

### Prediction Rule

$$
\hat{y} = \arg\max_i P(y=i|x)
$$

### Example

If probabilities are:

$$
[0.10,\;0.75,\;0.15]
$$

Then:

$$
\hat{y}=2
$$

because 0.75 is the highest probability.

---

# Sigmoid vs Softmax

| Feature | Sigmoid | Softmax |
|----------|----------|----------|
| Output Range | 0 to 1 | 0 to 1 |
| Number of Outputs | One | Multiple |
| Sum of Probabilities | Not necessarily 1 | Always 1 |
| Use Case | Binary Classification | Multi-Class Classification |
| Formula | $\sigma(z)=\frac{1}{1+e^{-z}}$ | $\frac{e^{z_i}}{\sum e^{z_j}}$ |

### Sigmoid Formula

$$
\sigma(z)=\frac{1}{1+e^{-z}}
$$

### Softmax Formula

$$
P(y=i|x)=\frac{e^{z_i}}{\sum_{j=1}^{K}e^{z_j}}
$$



# Summary

- **Softmax Regression** is used for multi-class classification.
- It converts class scores into probabilities using the Softmax function.
- Training minimizes **Cross-Entropy Loss**.
- Prediction is made using the **argmax** of probabilities.
- **Sigmoid** is for binary classification, while **Softmax** is for multi-class classification.

In [1]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
 df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [6]:
df = df[['sepal_length','petal_length','species']]

In [7]:
df.head()

   sepal_length  petal_length  species
0           5.1           1.4        0
1           4.9           1.4        0
2           4.7           1.3        0
3           4.6           1.5        0
4           5.0           1.4        0

In [8]:
X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [10]:
clf = LogisticRegression( multi_class = 'multinomial')

In [11]:
clf.fit(X_train,y_train)

/opt/homebrew/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(multi_class='multinomial')

In [12]:
y_pred = clf.predict(X_test)

In [13]:
print(accuracy_score(y_test,y_pred))

0.9666666666666667

In [14]:
pd.DataFrame(confusion_matrix(y_test,y_pred))

    0  1  2
0  14  0  0
1   0  7  1
2   0  0  8

In [15]:
# prediction
query = np.array([[3.4,2.7]])
clf.predict_proba(query)

/opt/homebrew/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[7.25865651e-01, 2.73720718e-01, 4.13631316e-04]])

In [16]:
clf.predict(query)

/opt/homebrew/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])