# Dropping Data

In [3]:
import pandas as pd
import numpy as np
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [4]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [5]:
obj.drop(['d','a'])

b    1.0
c    2.0
e    4.0
dtype: float64

In [7]:
# Dropping data from any axis
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [9]:
data.drop('three',axis = 1)

          one  two  four
Ohio        0    1     3
Colorado    4    5     7
Utah        8    9    11
New York   12   13    15

In [10]:
data.drop(index = ['Colorado','Ohio'])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [11]:
data.drop(['two','four'],axis = 1)

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [12]:
data.drop(columns = ['one','four'])

          two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [13]:
# SLicing and Viewing

# slices are views---> reference original data
# modifying slice --->changes original array
# use .copy() for independent data
# memory efficient but can cause bugs

# View : Reference to data(no copy) - Copy:Independent duplicate

In [14]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [18]:
obj.iloc[[0, 1]]

a    0.0
b    1.0
dtype: float64

In [19]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [20]:
obj.loc[['b','c']] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [21]:
df = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=["Ohio", "Colorado", "Utah", "New York"],
columns=["one", "two", "three", "four"])
df

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [22]:
df['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [23]:
df[1:3]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [24]:
df<5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [25]:
df.loc['Colorado']

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [28]:
df.loc[['Colorado','Utah']]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [29]:
# Arthemetic and Data Allignment
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
    index=["a", "c", "e", "f", "g"])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [30]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [31]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [33]:
df1 = pd.DataFrame(np.arange(9.0).reshape((3,3)),columns = list('bcd'),
                   index = ['Ohio','Texas','Colorado'])
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [38]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
index=["Utah", "Ohio", "Texas", "Oregon"])
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

#

In [36]:
df1+df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [39]:
# Arthemetic methods to fill the values
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                   columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                   columns = list('abcde'))
df2.loc[1,'b'] = np.nan
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [40]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [41]:
df1+df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [42]:
df1.add(df2,fill_value = 0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

# Operation Between DataFrame and Series

In [43]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns = list('bde'),
                     index = ['Utah','Ohio','Texas','Oregon'])
series = frame.iloc[0]
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [44]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [45]:
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [46]:
series2 = pd.Series(np.arange(3),index = list('bef'))
series2

b    0
e    1
f    2
dtype: int64

In [47]:
frame+series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [48]:
frame  = pd.DataFrame(np.random.standard_normal((4,3)),
                      columns = list('bde'),
                      index = ['Utah','Ohio','Texas','Oregon'])
frame

               b         d         e
Utah    0.019514 -0.116788  1.324252
Ohio   -0.518956 -1.731811 -1.170440
Texas  -0.569477  0.199553 -1.040159
Oregon  1.446027 -1.119224  1.140710

In [49]:
np.abs(frame)

               b         d         e
Utah    0.019514  0.116788  1.324252
Ohio    0.518956  1.731811  1.170440
Texas   0.569477  0.199553  1.040159
Oregon  1.446027  1.119224  1.140710

In [51]:
def f1(x):
    return x.max() - x.min()

In [52]:
frame.apply(f1)

b    2.015504
d    1.931364
e    2.494692
dtype: float64

In [53]:
frame.apply(f1,axis = 'columns')

Utah      1.441040
Ohio      1.212855
Texas     1.239712
Oregon    2.565252
dtype: float64

In [54]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])
frame.apply(f2)

            b         d         e
min -0.569477 -1.731811 -1.170440
max  1.446027  0.199553  1.324252

In [55]:
def my_format(x):
    return f"{x:.2f}"
frame.map(my_format)


# apply() ---> applies a function column-wise or row-wise
# map() ----> applies a function to each individual elements

            b      d      e
Utah     0.02  -0.12   1.32
Ohio    -0.52  -1.73  -1.17
Texas   -0.57   0.20  -1.04
Oregon   1.45  -1.12   1.14

In [56]:
frame

               b         d         e
Utah    0.019514 -0.116788  1.324252
Ohio   -0.518956 -1.731811 -1.170440
Texas  -0.569477  0.199553 -1.040159
Oregon  1.446027 -1.119224  1.140710

# Sorting and Ranking

In [57]:
obj = pd.Series(np.arange(4),index = list('dabc'))
obj

d    0
a    1
b    2
c    3
dtype: int64

In [58]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [59]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                     index = ['three','one'],
                     columns = list('dabc'))
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [61]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [62]:
frame.sort_index(axis = 1)

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [63]:
frame.sort_index(axis = 'columns',ascending = False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

# Sorting and Ranking

In [64]:
obj = pd.Series(np.arange(4),index = list('dabx'))
obj

d    0
a    1
b    2
x    3
dtype: int64

In [65]:
obj.sort_index()

a    1
b    2
d    0
x    3
dtype: int64

In [66]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
index=["three", "one"],
columns=["d", "a", "b", "c"])
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [68]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [70]:
frame = pd.DataFrame({
    'b':[4,7,-3,2],
    'a':[0,1,0,1]
})
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [71]:
frame.sort_values('b')

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [74]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [75]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [76]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1], "c": [-2, 5, 8, -2.5]})
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [77]:
frame.rank(axis = 'columns')

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [78]:
# Summarizing and Computing Descriptive Statistics

In [79]:
import pandas as pd
import numpy as np
df = pd.DataFrame([[1.2,np.nan],[7.1,-4.5],
                   [np.nan,np.nan],[0.75,-1.3]],
                  index = list('abcd'),
                  columns = ['one','two'])
df

    one  two
a  1.20  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [80]:
df.sum()

one    9.05
two   -5.80
dtype: float64

In [81]:
df.sum(axis = 1)

a    1.20
b    2.60
c    0.00
d   -0.55
dtype: float64

In [84]:
df.sum(axis = 'index',skipna =False ) # skipna tells how the missing values are handled
       # if skipna is true it ignores the nan values and the sum is normal
       # if skipna is false then is any nan exist then the sum is nan

one   NaN
two   NaN
dtype: float64

In [85]:
df.sum(axis = 'columns',skipna  = False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [86]:
df.mean(axis = 1)

a    1.200
b    1.300
c      NaN
d   -0.275
dtype: float64

In [87]:
df.idmax()

AttributeError: 'DataFrame' object has no attribute 'idmax'

In [89]:
df.cumsum  # it calculates the cumulative sum

<bound method DataFrame.cumsum of     one  two
a  1.20  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3>

In [90]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.016667 -2.900000
std    3.543421  2.262742
min    0.750000 -4.500000
25%    0.975000 -3.700000
50%    1.200000 -2.900000
75%    4.150000 -2.100000
max    7.100000 -1.300000

# Categorical Data Tools

In [91]:
obj = pd.Series(["a", "a", "b", "c"] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [92]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [93]:
df.prod()

one    6.39
two    5.85
dtype: float64

In [94]:
df

    one  two
a  1.20  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [98]:
df.prod(axis =1)

a     1.200
b   -31.950
c     1.000
d    -0.975
dtype: float64

In [99]:
df.diff()

   one  two
a  NaN  NaN
b  5.9  NaN
c  NaN  NaN
d  NaN  NaN

# Correlation and Covariance

In [102]:
#Unique Values,Value Counts and Membership

In [103]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [104]:
unique = obj.unique()
unique

array(['c', 'a', 'd', 'b'], dtype=object)

In [105]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [107]:
to_match = pd.Series(list('cabbca'))
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [108]:
uq = pd.Series(list('cba'))
uq

0    c
1    b
2    a
dtype: object

In [109]:
indices = pd.Index(uq).get_indexer(to_match)

In [110]:
indices

array([0, 2, 1, 1, 0, 2])

In [115]:
obj.value_counts

<bound method IndexOpsMixin.value_counts of 0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object>

In [116]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4], 
                     "Qu2": [2, 3, 1, 2, 3],
                     "Qu3": [1, 5, 2, 4, 4]})
data

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [117]:
data['Qu1'].value_counts()

Qu1
3    2
4    2
1    1
Name: count, dtype: int64

In [118]:
data['Qu1'].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [119]:
result = data.value_counts()
result

Qu1  Qu2  Qu3
1    2    1      1
3    2    4      1
     3    5      1
4    1    2      1
     3    4      1
Name: count, dtype: int64